### ISSUE TITLE
warning: error loading resource templates: Method not Found

### ISSUE THREAD

**Issue by stevenalanstark** [translated/lara-mcp#8]
I'm unsure if this is a valid report or not, but I wanted to share anyhow

I am using continue.dev with a local agent and have configured lara as a MCP server in the continue.dev extension

in the extension UI, I see a yellow warning icon with the tooltip error:

```
Error loading resource templates for MPC Server lara: MCP error -32601: Method not found

```

I named this MPC server `lara`, which is shown in the error.

I can use it still, since this is only a warning.

**Comment by CristianBelli01k** [comment]
Thanks @stevenalanstark for the report.
We're investigating.

**Comment by CristianBelli01k** [comment]
Hi @stevenalanstark, we attempted to replicate the issue but were unable to reproduce it.
Could you please share more details about how you configured the MCP Server?

**Comment by stevenalanstark** [comment]
@CristianBelli01k I'd be happy to, thank you for taking a look

<img width="430" alt="Image" src="https://github.com/user-attachments/assets/4e2e4751-e1d1-4f52-8c38-687db264a6e2" />

MCP Config:

```yaml
name: lara
version: 0.0.1
schema: v1
mcpServers:
  - name: lara
    command: npx
    args:
      - -y
      - "@translated/lara-mcp@latest"
    env: {
      "LARA_ACCESS_KEY_ID": "KEY",
      "LARA_ACCESS_KEY_SECRET": "KEY_SECRET"
    }

```

with continue.dev, I can load the developer tools to see the web inspector and JS logs, but that's more helpful for the actual execution, but I don't see how to find the detailed logs for the MCP servers just yet, else I'd add those as well. 

the error shows on both VS Code and JetBrains versions of continue.dev ( and I try to use the beta release as well, so it might just be on the continue.dev's side )

but I don't see any issues with using the tool itself, and the LLM can see the tools as well as the two @context actions.

please note that this is running in `agent` mode, otherwise continue.dev is unable to use custom tools
